"""Install an `lzo` compatibility shim backed by `lzokay`.

`paa_to_png` does `import lzo` and calls `lzo.decompress(data, 0, N)`.
The canonical `python-lzo` package has no prebuilt wheels for Windows
Python 3.14+ (building requires MSVC + liblzo2 headers).

`lzokay` ships pure-Python LZO1X decoding. This helper writes a small
`lzo.py` into user site-packages so `import lzo` resolves to lzokay.

This is a one-time environment helper, not part of conversion. It is
opt-in: run it only when you need LZO-compressed DXT mipmaps and cannot
install `python-lzo`.
"""

from __future__ import annotations

import os
import site
import sys

from .errors import MissingDependencyError

SHIM_SOURCE = '''"""Shim: redirects `import lzo` to `lzokay`.

Generated by dayz_3d_viewer.install_lzo_shim.

python-lzo signature: decompress(data, startpos=0, output_buffer_length=N)
lzokay signature:     decompress(data, expected_size=None)
"""
import lzokay

def decompress(data, startpos=0, output_buffer_length=None):
    if startpos > 0:
        data = data[startpos:]
    if output_buffer_length is not None:
        return lzokay.decompress(data, output_buffer_length)
    return lzokay.decompress(data)

def compress(data, level=1):
    return lzokay.compress(data)

__version__ = "shim-lzokay"
'''


def _candidate_site_paths():
    paths = []
    user_site = site.getusersitepackages()
    if user_site:
        paths.append(user_site)
    for item in sys.path:
        if item.endswith("site-packages") and item not in paths:
            paths.append(item)
            break
    return paths


def install_lzo_shim() -> int:
    try:
        import lzokay  # noqa: F401
    except ImportError as exc:
        raise MissingDependencyError(
            "lzokay is not installed. Install it first: pip install 'dayz-3d-viewer[lzo]'"
        ) from exc

    try:
        import lzo as existing_lzo
    except ImportError:
        existing_lzo = None
    if existing_lzo is not None:
        version = getattr(existing_lzo, "__version__", "unknown")
        if "shim" not in str(version):
            print("Real python-lzo already installed (version=%s)." % version)
            print("Shim install skipped.")
            return 0

    for directory in _candidate_site_paths():
        target = os.path.join(directory, "lzo.py")
        try:
            os.makedirs(directory, exist_ok=True)
            with open(target, "w", encoding="utf-8", newline="\n") as handle:
                handle.write(SHIM_SOURCE)
            print("Installed shim: %s" % target)
            return 0
        except OSError as exc:
            print("Failed to write to %s: %s" % (target, exc), file=sys.stderr)
            continue
    print("ERROR: could not find a writable site-packages directory.", file=sys.stderr)
    return 1


def main(argv=None):
    del argv
    return install_lzo_shim()
